[package]
name = "nomad-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Substrate
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
sp-std = { version = "4.0.0-dev", default-features = false }
sp-core = { version = "4.0.0-dev", default-features = false }
sp-io = { version = "4.0.0-dev", default-features = false }
sp-runtime = { version = "4.0.0-dev", default-features = false }
sp-runtime-interface = { version = "4.0.0-dev", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
parity-util-mem = { version = "0.10.2", default-features = false, features = ["primitive-types"] }

tiny-keccak = { version = "2.0.2", default-features = false }

[dependencies.signature]
path = "../signature"
default-features = false

[dependencies.ethers-signers]
version = "0.13.0"
default-features = false
optional = true

[dependencies.ethers-core]
version = "0.13.0"
default-features = false
optional = true

[dependencies.async-trait]
version = "0.1.42"
default-features = false
optional = true

[features]
default = ["std"]
std = []
testing = [
	"ethers-signers",
	"ethers-core",
	"async-trait",
	"signature/testing"
]